### PR TITLE
chit-chat-refinements

### PR DESCRIPTION
**Pull request by Vreejack**
Expansion and rationalization of some of the chit-chats for school skirts.

Trying to create more realistic and varied responses from Hermione when she is forced to expose herself.

### CODE REVIEW

**Comment by Vreejack** [comment]
Side issue... every English girl I have ever known was far more likely to refer to her underwear as "knickers" or "pants" than "panties," and would more likely refer to her "bum" (an old corruption of "bottom") than her ass. Our Hermione talks like an American.

**Comment by asease1** [comment]
Try to talk with Johnny or merlin they have a better understanding of the writing style of the game than me.

**Comment by Vreejack** [comment]
Right, it's jarring to have a sudden shift. It's just that in my head she talks like an English girl, which, as I discovered in my younger days can lead to exasperating failures in communication. The English/American difference in the word "fanny" can be particularly hilarious. But changing Hermione to speak like an actual English girl would be a project.

**Comment by Vreejack** [comment]
Just realized that panties are locked until whoring==12, so some code is unnecessary. I also wanted to absolutely require panties for some skirts until Hermione is a bloody great slut. At the moment I simply make her put panties on, but the player can immediately remove them. But like with the open leather jacket we can just pretend she covers up when she leaves D's tower.

**Comment by Johnny28** [comment]
I try to keep it consistent and accessible. Try not to use americanized way of speaking but I also try not to use some english terms that people outside the UK would'nt know so that the game is more accessible. Like "knickers", "cunny" for example. You've used a bunch of terms and ways of speaking that isn't consistent with how Hermione talks in the rest of the game.

Personally I also try not to drop in public favour elements outside that branch as it's supposed to be optional. It's a bit weird to have Hermione talk about other boys when you equip clothes for her if thats not the path you've chosen.

**Comment by Vreejack** [comment]
I understand your point about the language; am revising as I go.

But the path is important; I'll have to reconsider some of the dialogue, definitely split it for the two paths. The problem with these very short skirts is that just wearing them implies an extreme and immersion-breaking exhibitionist streak. But that's been true of Akabur's other games as well. Still, schoolgirl != slave. 

I think I can see four effective paths, here, split off by public shaming
1. D's whore (original)
2. Common whore (original)
3. D's naked slave whore (shamed)
4. Common Free Use Cum Dumpster (shamed)

No. 4 would have a similar ending to no. 2, but no. 3 would need a new ending -- a hybrid of nos. 1 and 2 in which she exposes herself at the podium but does not engage in a GB. There might already be enough art to cobble it together with careful stitching. A project for another day.

**Pull request closed without merging**
