### PR TITLE
Fix panty toggle

### PR DESCRIPTION
**Pull request by Vreejack**
It's a one-line fix.

All the checkboxes in the wardrobe destroy the paperdoll; the toggle is supposed to turn it back on. All the toggles do so except for panties. This adds in the missing line and fixes the problem.

If you don't believe me try deleting the same code from the other toggles. It produces the same kind of bug.

### CODE REVIEW

**Comment by Vreejack** [comment]
Problem is the code in main does not get called while you are in wardrobe, so code was probably added to each of the toggles. I'm not claiming it's a great design; I only point out that one of the toggles is missing this code and producing an obvious bug.

**Comment by asease1** [comment]
what code is not call the only thing you have add is 
`show screen hermione_main`
but just under it you have call her_main which hide that screen as the first call and then as one of the lass shows it again so that would make that command redundant and if that not the case then there is another problem

**Comment by Vreejack** [comment]
Well that's true, too. And weird.
So now I am intrigued.
Inserting the "redundant" code cures the problem. I shall study it until I have an answer.

**Comment by Vreejack** [comment]
I got suspicious that no one else seemed to even notice the problem. Seems to have been a corrupted save game. Once I started a new game there was no problem.
Of course, this leads to the question of how my save got corrupted, but I'll worry about that if it comes back.

**Comment by asease1** [comment]
it would be weird if that part did corrupt your save, was it corrupt after you insert a new update or what happens? and if you find a solution I more then happy to look at it^^

**Pull request closed without merging**
